### ISSUE TITLE
Plugin 'FTPClient' failed to load

### ISSUE THREAD

**Issue by dmiklic** [crimoniv/FTPClient#1]
After the most recent fman update (on Ubuntu 16.04) I get the following error when starting fman:
```
Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 125, in load
  File "fman/impl/plugins/plugin.py", line 141, in _load
  File "fman/impl/plugins/plugin.py", line 164, in _load_classes
  File "fman/impl/plugins/plugin.py", line 229, in _load_packages
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/damjan/.config/fman/Plugins/Third-party/FTPClient/ftpclient/__init__.py", line 6, in <module>
    from .listeners import FtpListener
  File "/home/damjan/.config/fman/Plugins/Third-party/FTPClient/ftpclient/listeners.py", line 4, in <module>
    from core.commands import _open_local_file
ImportError: cannot import name '_open_local_file'
```

**Comment by staatzstreich** [comment]
Same here on Mac OS Mojave. New User of fman, since today. Any news on this topic?

Plugin 'FTPClient' failed to load.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 125, in load
  File "fman/impl/plugins/plugin.py", line 141, in _load
  File "fman/impl/plugins/plugin.py", line 164, in _load_classes
  File "fman/impl/plugins/plugin.py", line 229, in _load_packages
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michaelstaatz/Library/Application Support/fman/Plugins/Third-party/FTPClient/ftpclient/__init__.py", line 6, in <module>
    from .listeners import FtpListener
  File "/Users/michaelstaatz/Library/Application Support/fman/Plugins/Third-party/FTPClient/ftpclient/listeners.py", line 4, in <module>
    from core.commands import _open_local_file
ImportError: cannot import name '_open_local_file'

**Comment by RiskyRaccoon** [comment]
I got the following error:
![image](https://user-images.githubusercontent.com/25715162/61718317-9a887d00-ad17-11e9-8d07-e7acc6244ba2.png)

**Comment by sstenn** [comment]
Any updates on this issue? I get this error everytime on startup.

    Plugin 'FTPClient' failed to load.

    Traceback (most recent call last):
    File "fman/impl/plugins/plugin.py", line 125, in load
    File "fman/impl/plugins/plugin.py", line 141, in _load
    File "fman/impl/plugins/plugin.py", line 164, in _load_classes
    File "fman/impl/plugins/plugin.py", line 229, in _load_packages
    File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
    File "<frozen importlib._bootstrap_external>", line 823, in load_module
    File "<frozen importlib._bootstrap_external>", line 682, in load_module
    File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 684, in _load
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/stenjansen/Library/Application Support/fman/Plugins/Third- 
    party/FTPClient/ftpclient/__init__.py", line 6, in <module>
    from .listeners import FtpListener
    File "/Users/stenjansen/Library/Application Support/fman/Plugins/Third- 
    party/FTPClient/ftpclient/listeners.py", line 4, in <module>
    from core.commands import _open_local_file
    ImportError: cannot import name ‘_open_local_file'

**Comment by spajdo** [comment]
same problem here... 
Any updates?

**Comment by AlfonsNiederhofer** [comment]
Hi,

installing plugins worked out of the box so far for different plugins.
With FTPClient I got the error below. Does anyone know the reason for that issue?

Thanks, Alfons

`Plugin 'FTPClient' failed to load.

Traceback (most recent call last):
File "fman/impl/plugins/plugin.py", line 125, in load
File "fman/impl/plugins/plugin.py", line 141, in _load
File "fman/impl/plugins/plugin.py", line 164, in _load_classes
File "fman/impl/plugins/plugin.py", line 229, in _load_packages
File "", line 399, in _check_name_wrapper
File "", line 823, in load_module
File "", line 682, in load_module
File "", line 265, in _load_module_shim
File "", line 684, in _load
File "", line 665, in _load_unlocked
File "", line 678, in exec_module
File "", line 219, in _call_with_frames_removed
File "/home/alfons/.config/fman/Plugins/Third-party/FTPClient/ftpclient/init.py", line 6, in
from .listeners import FtpListener
File "/home/alfons/.config/fman/Plugins/Third-party/FTPClient/ftpclient/listeners.py", line 4, in
from core.commands import _open_local_file
ImportError: cannot import name '_open_local_file`

**Comment by ghost** [comment]
Any chance this can be fixed? Ever?

**Comment by jcpeterson** [comment]
bump

**Comment by sschwarzer** [comment]
It seems that @mstaatz contributed a fix for this ticket at https://github.com/crimoniv/FTPClient/pull/2 / https://github.com/crimoniv/FTPClient/pull/2/commits/422b38a323e50b264744bffc69702efd57acbdd4 . You can install the `master` branch of @mstaatz 's repository: https://github.com/mstaatz/FTPClient to get the fix (although of course it would be even better if the fix got integrated in @crimoniv 's repository here).

That said, it's possible that meanwhile other things have changed in fman's plugin API, but I guess it's worth it to try @mstaatz 's repo.
